#!/bin/bash

svg="$1"

# Scale numbers
# This is still dumb, it should not be applied everywhere
perl -i -pe 's{(?<![\d#])(\d{5,}(?:\.\d+)?)(?!\d)}{sprintf("%.1f", $1/1000);}ge' "$svg"

# Fix numbers with double floating poing
sed -i "s/\.\([0-9]\+\)\.[0-9]\+/.\1/g" "$svg"

# rsvg-convert -a -w 500 -f svg $svg > .tmp.svg
# mv .tmp.svg $svg
