#!/bin/bash

# Wrapper for the plotPCB.py script
# It should work on Linux, Mac and possibly on Windows

readlink_osx()
{
	TARGET_FILE=$1

	cd $(dirname "$TARGET_FILE")
	TARGET_FILE=$(basename "$TARGET_FILE")

	# Iterate down a (possible) chain of symlinks
	while [ -L "$TARGET_FILE" ]
	do
		TARGET_FILE=$(readlink "$TARGET_FILE")
		cd $(dirname "$TARGET_FILE")
		TARGET_FILE=$(basename "$TARGET_FILE")
	done

	# Compute the canonicalized name by finding the physical path
	# for the directory we're in and appending the target file.
	PHYS_DIR=$(pwd -P)

	RESULT="$PHYS_DIR/$TARGET_FILE"

	echo $RESULT
}


case $OSTYPE in

	# MaxOS
	darwin*)
		SCRIPT=$(readlink_osx $0)
		SCRIPTPATH=$(dirname $SCRIPT)
		/Applications/Kicad/kicad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python ${SCRIPTPATH}/plotPCB.py $*
		;;

	# Linux
	*)
		SCRIPT=$(readlink -f $0)
		SCRIPTPATH=$(dirname $SCRIPT)
		/usr/bin/env python3 ${SCRIPTPATH}/plotPCB.py $*
		;;

esac
