# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 1.0.1 on Mon Feb 14 16:54:28 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class CommitsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CommitsDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("KiDiff - Select Commits to Compare")
        self.SetFocus()

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 4)

        self.main_group = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "GIT Repository"), wx.VERTICAL)
        sizer_3.Add(self.main_group, 1, wx.ALL | wx.EXPAND, 6)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        self.main_group.Add(sizer_5, 1, wx.ALL | wx.EXPAND, 4)

        self.board_path = wx.StaticText(self, wx.ID_ANY, "/kicad/project/path/board.kicad_pcb")
        sizer_5.Add(self.board_path, 0, wx.ALL, 4)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Commit 1 (a)"), wx.HORIZONTAL)
        sizer_5.Add(sizer_6, 1, wx.ALL | wx.EXPAND, 4)

        self.commits_list_1 = wx.ListCtrl(self, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.LC_ALIGN_LEFT | wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_SORT_DESCENDING)
        self.commits_list_1.SetMinSize((761, 162))
        self.commits_list_1.SetFont(wx.Font(10, wx.FONTFAMILY_MODERN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.commits_list_1.AppendColumn("#", format=wx.LIST_FORMAT_LEFT, width=25)
        self.commits_list_1.AppendColumn("Commits", format=wx.LIST_FORMAT_LEFT, width=1000)
        sizer_6.Add(self.commits_list_1, 1, wx.ALL | wx.EXPAND, 4)

        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Commit 2 (b)"), wx.HORIZONTAL)
        sizer_5.Add(sizer_7, 1, wx.ALL | wx.EXPAND, 4)

        self.commits_list_2 = wx.ListCtrl(self, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL)
        self.commits_list_2.SetMinSize((761, 162))
        self.commits_list_2.SetFont(wx.Font(10, wx.FONTFAMILY_MODERN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.commits_list_2.AppendColumn("#", format=wx.LIST_FORMAT_LEFT, width=25)
        self.commits_list_2.AppendColumn("Commits", format=wx.LIST_FORMAT_LEFT, width=1000)
        sizer_7.Add(self.commits_list_2, 1, wx.ALL | wx.EXPAND, 4)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 11)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetFocus()
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        # end wxGlade

# end of class CommitsDialog
